default: &default
  adapter: postgresql
  pool: 20
  port: 5432
  username: <%= ENV['MINES_DATABASE_USERNAME'] %>
  password: <%= ENV['MINES_DATABASE_PASSWORD'] %>
  encoding: utf8

development:
  <<: *default
  database: mines_development

test:
  <<: *default
  database: mines_test

production:
  <<: *default
  database: mines_production
